# Generated by Django 5.2.10 on 2026-01-15 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Region code (e.g., ame, anz)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full region name', max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LandCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Projection year')),
                ('value', models.FloatField(help_text='Projected value')),
                ('unit', models.CharField(choices=[('ha', 'Hectares'), ('t', 'Tonnes'), ('t/ha', 'Tonnes per Hectare')], max_length=20)),
                ('item', models.CharField(help_text='Item type', max_length=10)),
                ('variable', models.CharField(help_text='Variable type', max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.region')),
            ],
            options={
                'verbose_name': 'Land Cover Projection',
                'verbose_name_plural': 'Land Cover Projections',
                'ordering': ['region', 'item', 'year'],
                'indexes': [models.Index(fields=['region', 'item', 'year'], name='dashboard_l_region__6e4d64_idx')],
            },
        ),
        migrations.CreateModel(
            name='CropModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Projection year')),
                ('value', models.FloatField(help_text='Projected value')),
                ('unit', models.CharField(choices=[('ha', 'Hectares'), ('t', 'Tonnes'), ('t/ha', 'Tonnes per Hectare')], max_length=20)),
                ('item', models.CharField(help_text='Item type', max_length=10)),
                ('variable', models.CharField(help_text='Variable type', max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.region')),
            ],
            options={
                'verbose_name': 'Crop Module Projection',
                'verbose_name_plural': 'Crop Module Projections',
                'ordering': ['region', 'item', 'variable', 'year'],
                'indexes': [models.Index(fields=['region', 'item', 'year'], name='dashboard_c_region__fe0d08_idx'), models.Index(fields=['item', 'variable'], name='dashboard_c_item_857681_idx')],
            },
        ),
        migrations.CreateModel(
            name='BioenergyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Projection year')),
                ('value', models.FloatField(help_text='Projected value')),
                ('unit', models.CharField(choices=[('ha', 'Hectares'), ('t', 'Tonnes'), ('t/ha', 'Tonnes per Hectare')], max_length=20)),
                ('item', models.CharField(help_text='Item type', max_length=10)),
                ('variable', models.CharField(help_text='Variable type', max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.region')),
            ],
            options={
                'verbose_name': 'Bioenergy Module Projection',
                'verbose_name_plural': 'Bioenergy Module Projections',
                'ordering': ['region', 'item', 'variable', 'year'],
                'indexes': [models.Index(fields=['region', 'item', 'year'], name='dashboard_b_region__da9649_idx'), models.Index(fields=['item', 'variable'], name='dashboard_b_item_f5e298_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnimalModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Projection year')),
                ('value', models.FloatField(help_text='Projected value')),
                ('unit', models.CharField(choices=[('ha', 'Hectares'), ('t', 'Tonnes'), ('t/ha', 'Tonnes per Hectare')], max_length=20)),
                ('item', models.CharField(help_text='Item type', max_length=10)),
                ('variable', models.CharField(help_text='Variable type', max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dashboard.region')),
            ],
            options={
                'verbose_name': 'Animal Module Projection',
                'verbose_name_plural': 'Animal Module Projections',
                'ordering': ['region', 'item', 'variable', 'year'],
                'indexes': [models.Index(fields=['region', 'item', 'year'], name='dashboard_a_region__a40688_idx'), models.Index(fields=['item', 'variable'], name='dashboard_a_item_dd00e9_idx')],
            },
        ),
    ]
