# Generated by Django 5.2.10 on 2026-01-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='animalmodule',
            constraint=models.CheckConstraint(condition=models.Q(('item__in', ['rum', 'nrm', 'dry', 'grs'])), name='animalmodule_valid_item'),
        ),
        migrations.AddConstraint(
            model_name='animalmodule',
            constraint=models.CheckConstraint(condition=models.Q(('variable__in', ['area', 'prod', 'yild', 'cons', 'food', 'othu', 'expo', 'impo', 'nett'])), name='animalmodule_valid_variable'),
        ),
        migrations.AddConstraint(
            model_name='bioenergymodule',
            constraint=models.CheckConstraint(condition=models.Q(('item__in', ['sgc', 'pfb'])), name='bioenergymodule_valid_item'),
        ),
        migrations.AddConstraint(
            model_name='bioenergymodule',
            constraint=models.CheckConstraint(condition=models.Q(('variable__in', ['area', 'prod', 'yild', 'cons', 'othu', 'expo', 'impo', 'nett'])), name='bioenergymodule_valid_variable'),
        ),
        migrations.AddConstraint(
            model_name='cropmodule',
            constraint=models.CheckConstraint(condition=models.Q(('item__in', ['wht', 'ric', 'cgr', 'osd', 'vfn'])), name='cropmodule_valid_item'),
        ),
        migrations.AddConstraint(
            model_name='cropmodule',
            constraint=models.CheckConstraint(condition=models.Q(('variable__in', ['area', 'prod', 'yild', 'cons', 'food', 'feed', 'othu', 'expo', 'impo', 'nett'])), name='cropmodule_valid_variable'),
        ),
        migrations.AddConstraint(
            model_name='landcover',
            constraint=models.CheckConstraint(condition=models.Q(('item__in', ['crp', 'for', 'grs', 'nld'])), name='landcover_valid_item'),
        ),
        migrations.AddConstraint(
            model_name='landcover',
            constraint=models.CheckConstraint(condition=models.Q(('variable__in', ['land'])), name='landcover_valid_variable'),
        ),
    ]
