# Generated by Django 5.2.10 on 2026-01-16 00:31

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_item_variable_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalmodule',
            name='uuid',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='bioenergymodule',
            name='uuid',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='cropmodule',
            name='uuid',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='landcover',
            name='uuid',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), db_index=True, editable=False),
        ),
    ]
