# Generated by Django 6.0.1 on 2026-01-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_uuid_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animalmodule',
            options={'verbose_name': 'Animal Module Projection', 'verbose_name_plural': 'Animal Module Projections'},
        ),
        migrations.AlterModelOptions(
            name='bioenergymodule',
            options={'verbose_name': 'Bioenergy Module Projection', 'verbose_name_plural': 'Bioenergy Module Projections'},
        ),
        migrations.AlterModelOptions(
            name='cropmodule',
            options={'verbose_name': 'Crop Module Projection', 'verbose_name_plural': 'Crop Module Projections'},
        ),
        migrations.AlterModelOptions(
            name='landcover',
            options={'verbose_name': 'Land Cover Projection', 'verbose_name_plural': 'Land Cover Projections'},
        ),
    ]
